"""Emit Metal Shading Language (MSL) source from TritonGPU IR.

This module walks a TritonGPU MLIR module after the TTGIR pass pipeline
and produces MSL compute kernel source code.

Phase 1 targets the subset of ops needed for elementwise kernels:
- tt.get_program_id -> threadgroup_position_in_grid
- tt.make_range -> arithmetic on thread_position_in_threadgroup
- tt.addptr -> pointer arithmetic (device address space)
- tt.load / tt.store -> buffer reads/writes with bounds masking
- arith.addf/addi/mulf/muli -> MSL arithmetic operators
- arith.cmpi/cmpf -> comparison operators
"""

def emit_msl(mod, metadata, options):
    """Convert a TritonGPU IR module to MSL source code.

    Args:
        mod: The MLIR module after TTGIR passes.
        metadata: Compilation metadata dict (will be populated with kernel name).
        options: MetalOptions instance.

    Returns:
        MSL source code as a string.
    """
    # Get the textual MLIR representation and walk it.
    ir_text = str(mod)

    # For now, generate a placeholder kernel that demonstrates the pipeline
    # works end-to-end. The real emitter will parse TTGIR ops and emit
    # corresponding MSL.
    kernel_name = _extract_kernel_name(ir_text)
    metadata["name"] = kernel_name

    num_warps = options.num_warps
    threads_per_tg = num_warps * 32

    msl = _emit_placeholder_kernel(kernel_name, threads_per_tg)
    return msl


def _extract_kernel_name(ir_text):
    """Extract the kernel function name from MLIR text."""
    # Look for: tt.func public @kernel_name(
    import re

    match = re.search(r"tt\.func\s+public\s+@(\w+)\s*\(", ir_text)
    if match:
        return match.group(1)
    # Fallback: look for func.func @name
    match = re.search(r"func\.func\s+@(\w+)\s*\(", ir_text)
    if match:
        return match.group(1)
    return "triton_kernel"


def _emit_placeholder_kernel(kernel_name, threads_per_tg):
    """Emit a minimal MSL kernel for pipeline testing.

    This will be replaced with a real TTGIR-to-MSL translator.
    """
    return f"""\
#include <metal_stdlib>
using namespace metal;

// Placeholder kernel generated by triton-metal.
// This validates the MSL compilation pipeline works end-to-end.
kernel void {kernel_name}(
    device const float* input [[buffer(0)]],
    device float* output [[buffer(1)]],
    constant uint& n_elements [[buffer(2)]],
    uint tid [[thread_position_in_grid]],
    uint tgid [[threadgroup_position_in_grid]],
    uint lid [[thread_position_in_threadgroup]],
    uint tg_size [[threads_per_threadgroup]]
) {{
    uint idx = tgid * tg_size + lid;
    if (idx < n_elements) {{
        output[idx] = input[idx];
    }}
}}
"""
